import {httpStatusCodes} from './@types/http-status/index';

const httpCodes:httpStatusCodes = [

	{status: 100, statusText: 'Continue'},
	{status: 101, statusText: 'Switching Protocol'},
	{status: 103, statusText: 'Processing (WebDAV)'},
	{status: 200, statusText: 'OK'},
	{status: 201, statusText: 'Created'},
	{status: 202, statusText: 'Accepted'},
	{status: 203, statusText: 'Non-Authoritative Information'},
	{status: 204, statusText: 'No Content'},
	{status: 205, statusText: 'Reset Content'},
	{status: 206, statusText: 'Partial Content'},
	{status: 207, statusText: 'Multi-Status (WebDAV)'},
	{status: 208, statusText: 'Multi-Status (WebDAV)'},
	{status: 226, statusText: 'IM Used (HTTP Delta encoding)'},
	{status: 300, statusText: 'Multiple Choice'},
	{status: 301, statusText: 'Moved Permanently'},
	{status: 302, statusText: 'Found'},
	{status: 303, statusText: 'See Other'},
	{status: 304, statusText: 'Not Modified'},
	{status: 305, statusText: 'Use Proxy'},
	{status: 306, statusText: 'unused'},
	{status: 307, statusText: 'Temporary Redirect'},
	{status: 308, statusText: 'Permanent Redirect'},
	{status: 400, statusText: 'Bad Request'},
	{status: 401, statusText: 'Unauthorized'},
	{status: 402, statusText: 'Payment Required'},
	{status: 403, statusText: 'Forbidden'},
	{status: 404, statusText: 'Not Found'},
	{status: 405, statusText: 'Method Not Allowed'},
	{status: 406, statusText: 'Not Acceptable '},
	{status: 407, statusText: 'Proxy Authentication Required'},
	{status: 408, statusText: 'Request Timeout'},
	{status: 409, statusText: 'Conflict'},
	{status: 410, statusText: 'Gone'},
	{status: 411, statusText: 'Length Required'},
	{status: 412, statusText: 'Precondition Failed'},
	{status: 413, statusText: 'Payload Too Large'},
	{status: 414, statusText: 'URI Too Long'},
	{status: 415, statusText: 'Unsupported Media Type'},
	{status: 416, statusText: 'Requested Range Not Satisfiable'},
	{status: 417, statusText: 'Expectation Failed'},
	{status: 418, statusText: 'I\'m a teapot'},
	{status: 421, statusText: 'Misdirected Request'},
	{status: 422, statusText: 'Unprocessable Entity (WebDAV)'},
	{status: 423, statusText: 'Locked (WebDAV)'},
	{status: 424, statusText: 'Failed Dependency (WebDAV)'},
	{status: 426, statusText: 'Upgrade Required'},
	{status: 428, statusText: 'Precondition Required'},
	{status: 429, statusText: 'Too Many Requests'},
	{status: 431, statusText: 'Request Header Fields Too Large'},
	{status: 451, statusText: 'Unavailable For Legal Reasons'},
	{status: 500, statusText: 'Internal Server Error'},
	{status: 501, statusText: 'Not Implemented'},
	{status: 502, statusText: 'Bad Gateway'},
	{status: 503, statusText: 'Service Unavailable'},
	{status: 504, statusText: 'Gateway Timeout'},
	{status: 505, statusText: 'HTTP Version Not Supported'},
	{status: 506, statusText: 'Variant Also Negotiates'},
	{status: 507, statusText: 'Insufficient Storage'},
	{status: 508, statusText: 'Loop Detected (WebDAV)'},
	{status: 510, statusText: 'Not Extended'},
	{status: 511, statusText: 'Network Authentication Required'}

];

export default httpCodes;
